# Generated by Django 5.1.3 on 2024-11-25 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_userrole_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='awards_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workhistory_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.TextField(blank=True, null=True, verbose_name='受賞歴'),
        ),
        migrations.AddField(
            model_name='profile',
            name='challenges',
            field=models.TextField(blank=True, null=True, verbose_name='挑戦したいこと'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikes',
            field=models.TextField(blank=True, null=True, verbose_name='NGなこと'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(blank=True, null=True, verbose_name='ポートフォリオ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='スキル'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.TextField(blank=True, null=True, verbose_name='得意分野'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workhistory',
            field=models.TextField(blank=True, null=True, verbose_name='経歴'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agency_or_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='所属（事務所やグループ名）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='free_text',
            field=models.TextField(blank=True, null=True, verbose_name='フリー記述'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('選択しない', '選択しない')], default='選択しない', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
